Use pybind11 from PIP
I don't have the details about why exactly that version of pybind11 on
Ubuntu 20.04 broke down, but here's how it ended up on Ubuntu 22.04 when
trying to use Python 3.11:

 In file included from /usr/include/pybind11/cast.h:16,
                  from /usr/include/pybind11/attr.h:13,
                  from /usr/include/pybind11/pybind11.h:13,
                  from /usr/include/pybind11/functional.h:12,
                  from /home/runner/work/oopt-gnpy-libyang/oopt-gnpy-libyang/oopt-gnpy-libyang.cpp:1:
 /usr/include/pybind11/detail/type_caster_base.h: In function ‘std::string pybind11::detail::error_string()’:
 /usr/include/pybind11/detail/type_caster_base.h:482:26: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
   482 |             frame = frame->f_back;
       |                          ^~
 In file included from /opt/hostedtoolcache/Python/3.11.1/x64/include/python3.11/Python.h:42,
                  from /usr/include/pybind11/detail/common.h:215,
                  from /usr/include/pybind11/pytypes.h:12,
                  from /usr/include/pybind11/cast.h:13,
                  from /usr/include/pybind11/attr.h:13,
                  from /usr/include/pybind11/pybind11.h:13,
                  from /usr/include/pybind11/functional.h:12,
                  from /home/runner/work/oopt-gnpy-libyang/oopt-gnpy-libyang/oopt-gnpy-libyang.cpp:1:
 /opt/hostedtoolcache/Python/3.11.1/x64/include/python3.11/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct _frame’}
    22 | typedef struct _frame PyFrameObject;
       |                ^~~~~~

On Windows, it failed because (apparently) vcpkg patches Python
detection as per https://github.com/microsoft/vcpkg/issues/23796. The
build would fail like this (vcpkg Pytohn is 3.10, the system-selected
one is 3.11):

 CMake Error at C:/t/build-env-1a5f954n/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
   Could NOT find Python (missing: Development.Module) (found suitable version
   "3.11.1", minimum required is "3.8")
 Call Stack (most recent call first):
   C:/t/build-env-1a5f954n/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
   C:/t/build-env-1a5f954n/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/FindPython/Support.cmake:3245 (find_package_handle_standard_args)
   C:/t/build-env-1a5f954n/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/FindPython.cmake:519 (include)

So let's just use the PIP magic and hope for the best.